###
GET http://localhost:8080/
content-type: application/json

{
    "query": "phone",
    "page": 1
}

###
GET http://localhost:8080/
content-type: application/json

{
    "query": 2,
    "page": 1
}
###
GET http://localhost:8080/
content-type: application/json

{
    "query": "",
    "page": 1
}
###
GET http://localhost:8080/
content-type: application/json

{
    "query": 2,
    "page": "1"
}

###
GET http://localhost:8080/
content-type: application/json

{
    "query": "mac",
    "page": 1
}